config/routes.rb
Rails.application.routes.draw do
  # 管理者用のDeviseルート設定
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    resources :users, only: [:index, :show, :destroy]
    resources :comments, only: [:index, :destroy]
    resources :posts, only: [:index, :show, :destroy]
    resources :groups, only: [:index, :show, :destroy]
  end

  # 一般ユーザー用のルート設定
  scope module: :public do
    # Deviseのルート設定
    devise_for :users

    # ルート定義
    root to: 'homes#top'

    # 静的ページ
    get 'homes/about', to: 'homes#about', as: :about

    # 投稿とコメントのリソース
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorite, only: [:create, :destroy]
    end

    # ユーザーのリソース
    resources :users, only: [:index, :show, :edit, :update,] do
      resources :relationships, only: [:create, :destroy]
      member do
        get 'followings', to: 'relationships#followings'
        get 'followers', to: 'relationships#followers'
      end
      get :favorited_posts, on: :member
    end

    #グループのリソース
    resources :groups do
      resources :memberships, only: [:create, :destroy]
    end
    
    #ゲストユーザー用のルート設定
      devise_scope :user do
        post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
    end
  end

  # 検索ページ
  get 'search' => "searches#search"
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  
  validates :title, presence: true
  validates :text, presence: true, length: { maximum: 500 }
  
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
  
  def self.looks(search, word)
    if search == "perfect_match"
      @post = Post.where("title LIKE ? OR text LIKE ?", "#{word}", "#{word}")
    elsif search == "forward_match"
      @post = Post.where("title LIKE ? OR text LIKE ?", "#{word}%", "#{word}%")
    elsif search == "backward_match"
      @post = Post.where("title LIKE ? OR text LIKE ?", "%#{word}", "%#{word}")
    elsif search == "partial_match"
      @post = Post.where("title LIKE ? OR text LIKE ?", "%#{word}%", "%#{word}%")
    else
      @post = Post.all
    end
  end
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!
  layout 'admin'

  def index
    @posts = Post.all
  end 
  
  def show
    @post = Post.find(params[:id])
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path, notice: "投稿が削除されました"
  end
  
  private
  
  def authenticate_admin!
    unless admin_signed_in?
      redirect_to new_admin_session_path, alert: "管理者としてログインが必要です。"
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to post_path(@post.id)
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :image, :text, :problem, :explanation)
  end
  
  def is_matching_login_user
    @post = Post.find(params[:id])
    @user = @post.user
    unless @user == current_user
      redirect_to posts_path
    end
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>編集画面</h2>
      <% if @post.errors.any? %>
        <h3><%= @post.errors.count %>errors prohibited this obj from being saved:</h3>
        <ul>
          <% @post.errors.full_messages.each do |messages| %>
          <li><%= messages %></li>
          <% end %>
        </ul>
      <% end %>
      
      <%= form_with model: @post do |f| %>
        <div><label for="inputTitle">タイトル</label></div>
          <%= f.text_field :title,actofocus: true, id: "inputTitle", placeholder: "" %>
        <div>説明</div>
        <%= f.text_area :text %>
        <div>問題</div>
        <%= f.text_area :problem %>
        <div>解説</div>
        <%= f.text_area :explanation %>
        <div>画像</div>
        <%= f.file_field :image, accept: "image/*" %>
        <p></p>
        <div><%= f.submit '保存' %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container px-5 px-sm-0">
  <h2>Posts</h2>
  <table class = "table table-hover table-inverse">
    <thead>
      <tr>
        <th>タイトル</th>
        <th>説明</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
      <tr>
        <td>
          <%= link_to post_path(post.id) do %>
            <%= post.title %>
          <% end %>
        </td>
        <td>
          <%= post.text %>
        </td>
        <td>
          <%= "#{post.post_comments.count} コメント" %>
        </td>
        <td>
          <%= image_tag post.get_image, size: "100x100" %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>投稿フォーム</h2>
      <% if @post.errors.any? %>
      <h2><%= @post.errors.count %>errors prohibited this obj from being saved:</h2>
      <ul>
        <% @post.errors.full_messages.each do |messages| %>
          <li><%= messages %></li>
        <% end %>
      </ul>
      <% end %>
      <%= form_with model: @post do |f| %>
        <div><label for="inputTitle">タイトル</label></div>
        <%= f.text_field :title,actofocus: true, id: "inputTitle", placeholder: "" %>
        <p>説明</p>
        <%= f.text_area :text %>
        <p>問題</p>
        <%= f.text_area :problem %>
        <p>解説</p>
        <%= f.text_area :explanation %>
        <div><label for="inputImage">画像</label></div>
        <%= f.file_field :profile_image, placeholder: "画像", accept: "image/*" %>
        <p></p>
        <p><%= f.submit '投稿' %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container px-5 px-sm-5">
<h2>投稿詳細</h2>
<div>
  <p><%= image_tag @post.user.get_profile_image, size: "100x100" %>    <%=@post.user.name %></p>
  <p>タイトル:<%= @post.title %></p>
  <p>説明:<%= @post.text %></p>
  <p>問題:<%= @post.problem %></p>
  <p>解説:<%= @post.explanation %></p>
  <%= image_tag @post.get_image, size: "200x200" %>
  <p>投稿日:<%=@post.created_at.strftime('%Y/%m/%d') %></p>
  <p><%= "コメント件数 #{@post.post_comments.count}" %></p>
  <%= link_to "編集", edit_post_path(@post.id) %>
  <% if @post.user == current_user %>
    <%= link_to "削除", post_path(@post), method: :delete %>
  <% end %>
</div>
<table>
  <tbody>
      <% @post.post_comments.each do |post_comment| %>
      <tr>
        
        <td>
          <%= link_to user_path(post_comment.user) do %>
            <%= image_tag post_comment.user.get_profile_image, size: "100x100" %><br>
            <%= post_comment.user.name %>
          <% end %>
        </td>
        <td><%= post_comment.comment %></td>
        <td>
          <% if post_comment.user == current_user %>
            <%= link_to "Destroy", post_post_comment_path(@post, post_comment), method: :delete, class: "btn btn-danger pull-right" %>
          <% end %>
        </td>
      </tr>
      <% end %>
  </tbody>
</table>

<%= form_with(model:[@post, @post_comment], local: true) do |f| %>
  <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに", class: "w-100" %>
  <%= f.submit "送信" %>
<% end %>