config/routes.rb
Rails.application.routes.draw do
  # 管理者用のDeviseルート設定
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    resources :users, only: [:index, :show, :destroy]
    resources :comments, only: [:index, :destroy]
    resources :posts, only: [:index, :show, :destroy]
    resources :groups, only: [:index, :show, :destroy]
  end

  # 一般ユーザー用のルート設定
  scope module: :public do
    # Deviseのルート設定
    devise_for :users

    # ルート定義
    root to: 'homes#top'

    # 静的ページ
    get 'homes/about', to: 'homes#about', as: :about

    # 投稿とコメントのリソース
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorite, only: [:create, :destroy]
    end

    # ユーザーのリソース
    resources :users, only: [:index, :show, :edit, :update,] do
      resources :relationships, only: [:create, :destroy]
      member do
        get 'followings', to: 'relationships#followings'
        get 'followers', to: 'relationships#followers'
      end
      get :favorited_posts, on: :member
    end

    #グループのリソース
    resources :groups do
      resources :memberships, only: [:create, :destroy]
    end
    
    #ゲストユーザー用のルート設定
      devise_scope :user do
        post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
    end
  end

  # 検索ページ
  get 'search' => "searches#search"
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :memberships
  has_many :users, through: :memberships
  validates :name, presence: true
  validates :description, presence: true
  belongs_to :owner, class_name: 'User', foreign_key: 'owner_id'
end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < ApplicationController
  before_action :authenticate_admin
  layout 'admin'
  
  def index
    @groups = Group.all
  end 
  
  def show
    @group = Group.find(params[:id])
  end 
  
  def destroy
    @group = Group.find(params[:id])
    @group.destroy 
      flash[:notice] = "削除に成功しました"
    redirect_to admin_groups_path
  end 
  
  private
  
  def authenticate_admin
    unless admin_signed_in?
      redirect_to new_admin_ssesion_path, alert: "管理者としてログインが必要です。"
    end 
  end 
end

app/helpers/admin/groups_helper.rb
module Admin::GroupsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/admin/groups/index.html.erb
<div class="container px5 px-sm-0">
  <h2>グループ一覧</h2>
  <table class="table table-hover table-bordered custom-table" style="width: 100%; table-layout: fixed;">
    <thead>
      <tr>
        <th style="width: 20%;">グループ名</th>
        <th style="width: 70%;">説明</th>
        <th style="width: 10%;">人数</th>
      </tr>
    </thead>
    <tbody>
      <% @groups.each do |group| %>
        <tr onclick= "window.location='<%= admin_group_path(group.id) %>'" style="cursor: pointer;">
          <td data-label="グループ名" class="align-middle text-left" style="white-space: normal; word-wrap: break-word; overflow-wrap: break-word;">
            <%= truncate(group.name, length: 25, omission: '... ') %>
          </td>
          <td data-label="説明" class="align-middle text-left" style="white-space: normal; word-wrap: break-word; overflow-wrap: break-word;">
            <%= truncate(group.description, length: 95, omission: '... ') %>
          </td>
          <td data-label="人数" class="align-middle text-left">
            <%= "#{group.users.count} 人"  %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/groups/show.html.erb
<div class="container px5 px-sm-5">
  <h2 class="my-4">グループ詳細</h2>
  <div>
    <h3>グループ名:<%= @group.name %></h3>
    <h3>グループオーナー</h3>
      <div class="d-flex align-items-center mb-3">
        <%= link_to admin_user_path(@group.owner) do %>
          <%=image_tag @group.owner.get_profile_image, size: "100x100" %><br>
          <span class="text-dark"><%= @group.owner.name %></span>
        <% end %>
      </div>
    <p><strong>説明:</strong> <%= @group.description %></p>
  <%= link_to "削除", admin_group_path(@group.id), method: :delete, data: {confirm: "本当にグループを削除しますか？"}, class: "btn btn-danger" %>
  
  <h3>グループユーザー</h3>
    <table class="table table-hover table-bordered custom-table">
      <thead>
        <tr>
          <th>アイコン</th>
          <th>ユーザー名</th>
        </tr>
      </thead>
      <tbody>
        <% @group.memberships.each do |member| %>
          <tr onclick= "window.location='<%= user_path(member.user) %>'" style="cursor: pointer;">
            <td data-label="アイコン" class="align-middle text-left">
              <%= image_tag member.user.get_profile_image, size: "100x100" %>
            </td>
            <td data-label="ユーザー名" class="align-middle text-left">
              <%= member.user.name %>
           </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  <div><%= link_to '戻る', admin_groups_path, class: "btn btn-secondary mt-3" %></div>
  </div>
</div>