config/routes.rb
Rails.application.routes.draw do
  # 管理者用のDeviseルート設定
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    resources :users, only: [:index, :show, :destroy]
    resources :comments, only: [:index, :destroy]
    resources :posts, only: [:index, :show, :destroy]
    resources :groups, only: [:index, :show, :destroy]
  end

  # 一般ユーザー用のルート設定
  scope module: :public do
    # Deviseのルート設定
    devise_for :users

    # ルート定義
    root to: 'homes#top'

    # 静的ページ
    get 'homes/about', to: 'homes#about', as: :about

    # 投稿とコメントのリソース
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorite, only: [:create, :destroy]
    end

    # ユーザーのリソース
    resources :users, only: [:index, :show, :edit, :update,] do
      resources :relationships, only: [:create, :destroy]
      member do
        get 'followings', to: 'relationships#followings'
        get 'followers', to: 'relationships#followers'
      end
      get :favorited_posts, on: :member
    end

    #グループのリソース
    resources :groups do
      resources :memberships, only: [:create, :destroy]
    end
    
    #ゲストユーザー用のルート設定
      devise_scope :user do
        post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
    end
  end

  # 検索ページ
  get 'search' => "searches#search"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Devise modules
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def admin?
    self.admin
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  
  validates :user_id, uniqueness: {scope: :post_id}
  
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :memberships
  has_many :users, through: :memberships
  validates :name, presence: true
  validates :description, presence: true
  belongs_to :owner, class_name: 'User', foreign_key: 'owner_id'
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :group, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  
  validates :title, presence: true
  validates :text, presence: true, length: { maximum: 500 }
  
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
  
  def self.looks(search, word)
    if search == "perfect_match"
      @post = Post.where("title LIKE ? OR text LIKE ?", "#{word}", "#{word}")
    elsif search == "forward_match"
      @post = Post.where("title LIKE ? OR text LIKE ?", "#{word}%", "#{word}%")
    elsif search == "backward_match"
      @post = Post.where("title LIKE ? OR text LIKE ?", "%#{word}", "%#{word}")
    elsif search == "partial_match"
      @post = Post.where("title LIKE ? OR text LIKE ?", "%#{word}%", "%#{word}%")
    else
      @post = Post.all
    end
  end
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :groups, through: :memberships
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :post
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_one_attached :profile_image

  validates :name, presence: true, uniqueness: true, length: { in: 2..20 }

  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image
  end

  GUEST_USER_EMAIL = "guest@example.com"

    def self.guest
      find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
        user.password = SecureRandom.urlsafe_base64
        user.name = "guestuser"
      end
    end

    def guest_user?
      email == GUEST_USER_EMAIL
    end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?", "%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end
  
  def self.excluding_guest
    where.not(email: GUEST_USER_EMAIL)
  end
  
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end 
  
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end 
  
  def following?(user)
    followings.include?(user)
  end 
  
  def relationship_with(other_user)
  relationships.find_by(followed_id: other_user.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to post_path(@post.id)
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :image, :text, :problem, :explanation)
  end
  
  def is_matching_login_user
    @post = Post.find(params[:id])
    @user = @post.user
    unless @user == current_user
      redirect_to posts_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    case flash_type.to_sym
    when :notice
      "success"   # 成功時のメッセージには "alert-success" クラスを適用
    when :alert
      "danger"    # エラーメッセージには "alert-danger" クラスを適用
    else
      "info"      # その他のメッセージには "alert-info" クラスを適用
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin - Studu_Site</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <script src="https://kit.fontawesome.com/a8e490ee7d.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <%= link_to "管理者ページ", "#", class: "navbar-brand p-3" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ms-auto">
            <% if admin_signed_in? %>
            <li class="nav-item">
              <%= link_to admin_posts_path, class: 'nav-link text-light' do  %>
                <i class="fa-solid fa-comments"></i>Posts
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_users_path, class: 'nav-link text-light' do %>
                <i class="fa-solid fa-users"></i>Users
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_groups_path, class: 'nav-link text-light' do %>
                <i class="fa-solid fa-user-group"></i>Groups
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-light' do %>
                <i class="fa-solid fa-right-from-bracket"></i>Log out
              <% end %>
            </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    </header>
    <div class="container mt-4">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= bootstrap_class_for(key) %> alert-dismissible fade show" role="alert">
          <%= value %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Study Site</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <script src="https://kit.fontawesome.com/a8e490ee7d.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header>
      <nav class="navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to "Study Site", "/", class: "navbar-brand p-3" %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <dvi class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <div class="d-flex justify-content-center mb-2">
              <%= render 'searches/form' %>
            </div>
            <li class="nav-item">
              <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
                <i class="fa-solid fa-house"></i>Home
              <% end %>
            </li>
            </li>
            <li class="nav-item">
              <%= link_to new_post_path, class: 'nav-link text-light' do  %>
                <i class="fa-solid fa-comment"></i>Post
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to posts_path, class: 'nav-link text-light' do  %>
                <i class="fa-solid fa-comments"></i>Posts
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to users_path, class: 'nav-link text-light' do %>
                <i class="fa-solid fa-users"></i>Users
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to groups_path, class: 'nav-link text-light' do %>
                <i class="fa-solid fa-user-group"></i>Groups
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                <i class="fa-solid fa-right-from-bracket"></i>Log out
              <% end %>
            </li>

            <% else %>
            <li class="nav-item">
              <%= link_to root_path, class: 'nav-link text-light' do %>
                <i class="fa-solid fa-house"></i>Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to about_path,class: 'nav-link text-light' do %>
                <i class="fa-solid fa-link"></i>About
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_registration_path,class: 'nav-link text-light' do %>
                <i class="fa-solid fa-user-plus"></i>Sign up 
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path,class: 'nav-link text-light' do %>
                <i class="fa-solid fa-right-to-bracket"></i>Log in
              <% end %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <div class="container mt-4">
      <!-- フラッシュメッセージの表示 -->
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= bootstrap_class_for(key) %> alert-dismissible fade show" role="alert">
          <%= value %>
        </div>
      <% end %>

      <%= yield %> 
    </div>
    <main>
    </main>
    <footer >
      <div class='container mt-5'>
        <div class='row'>
          <div class='mx-auto'>
            <p></p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>